'use strict';

/** @type {import('sequelize-cli').Migration} */

module.exports = {
  async up (queryInterface, Sequelize) {
    const now = new Date().toISOString();

    await queryInterface.bulkInsert(
      'phones',
      [
        {
          model: 'iPhone 12',
          brand: 'Apple',
          manufactured_year: 2020,
          ram_size: 4000,
          cpu: 'Apple A14 Bionic',
          screen_diagonal: 6.1,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S20',
          brand: 'Samsung',
          manufactured_year: 2020,
          ram_size: 8000,
          cpu: 'Exynos 990',
          screen_diagonal: 6.2,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'N8',
          brand: 'Nokia',
          manufactured_year: 2010,
          ram_size: 512,
          cpu: 'ARM 11',
          screen_diagonal: 3.5,
          has_nfc: false,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S',
          brand: 'Samsung',
          manufactured_year: 2010,
          ram_size: 512,
          cpu: 'Hummingbird',
          screen_diagonal: 4.0,
          has_nfc: false,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'iPhone XS',
          brand: 'Apple',
          manufactured_year: 2018,
          ram_size: 4000,
          cpu: 'Apple A12 Bionic',
          screen_diagonal: 5.8,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S10',
          brand: 'Samsung',
          manufactured_year: 2019,
          ram_size: 8000,
          cpu: 'Exynos 9820',
          screen_diagonal: 6.1,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'iPhone 13',
          brand: 'Apple',
          manufactured_year: 2021,
          ram_size: 4000,
          cpu: 'Apple A15 Bionic',
          screen_diagonal: 6.1,
          has_nfc: false,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S21',
          brand: 'Samsung',
          manufactured_year: 2021,
          ram_size: 8000,
          cpu: 'Exynos 2100',
          screen_diagonal: 6.2,
          has_nfc: false,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Pixel 6',
          brand: 'Google',
          manufactured_year: 2021,
          ram_size: 8000,
          cpu: 'Google Tensor',
          screen_diagonal: 6.4,
          has_nfc: false,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'iPhone 14',
          brand: 'Apple',
          manufactured_year: 2022,
          ram_size: 6000,
          cpu: 'Apple A15 Bionic',
          screen_diagonal: 6.1,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S23',
          brand: 'Samsung',
          manufactured_year: 2023,
          ram_size: 8000,
          cpu: 'Snapdragon 8 Gen 2',
          screen_diagonal: 6.1,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Pixel 9',
          brand: 'Google',
          manufactured_year: 2024,
          ram_size: 12000,
          cpu: 'Google Tensor G4',
          screen_diagonal: 6.3,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'Galaxy S25',
          brand: 'Samsung',
          manufactured_year: 2025,
          ram_size: 12000,
          cpu: 'Snapdragon 8 Elite',
          screen_diagonal: 6.2,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
        {
          model: 'iPhone 16',
          brand: 'Apple',
          manufactured_year: 2025,
          ram_size: 8000,
          cpu: 'Apple A18',
          screen_diagonal: 6.1,
          has_nfc: true,
          created_at: now,
          updated_at: now,
        },
      ],
      {}
    );
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Phones', {
      model: [
        'iPhone 12',
        'Galaxy S20',
        'N8',
        'Galaxy S',
        'iPhone XS',
        'Galaxy S10',
        'iPhone 13',
        'Galaxy S21',
        'Pixel 6',
        'iPhone 14',
        'Galaxy S23',
        'Pixel 9',
        'Galaxy S25',
        'iPhone 16',
      ],
    });
  },
};
